

export const MenuList = [
  {
    id: 1,
    image:"../images/dashboard-svgrepo-com%201%20(1).svg",
    title: "Dashboard",
    url: "/dashboard",
    test: "this is dashboard",
  },
  {
    id: 2,
    image:"../images/organization.png",
    title: "Organization",
    url: "/Organization",
    test: "this is Organization",
  },
  {
    id: 3,
    image:"../images/employee.png",
    title: "Employees",
    url: "/Employees",
    test: "this is Employees",
  },
  {
    id: 4,
    image:"../images/assets.png",
    title: "Assets",
    url: "/Assets",
    test: "this is Assets",
  },
  {
    id: 5,
    image:"../images/icon_events.png",
    title: "Events",
    url: "/Events",
    test: "this is Events",
  },
  {
    id: 6,
    image:"../images/icon_polls.png",
    title: "Polls",
    url: "/Polls",
    test: "this is Polls",
  },
  {
    id: 7,
    image:"../images/icon_announcements.png",
    title: "Announcements",
    url: "/Announcements",
    test: "this is Announcements",
  },
  {
    id: 8,
    image:"../images/policies.png",
    title: "Policies",
    url: "/Policies",
    test: "this is Policies",
  },
  {
    id: 9,
    image:"../images/holidays.png",
    title: "Holidays",
    url: "/Holidays",
    test: "this is Holidays",
  },
  {
    id: 10,
    image:"../images/support.png",
    title: "Support",
    url: "/Support",
    test: "this is Support",
  },
  {
    id: 11,
    image:"../images/feedback.png",
    title: "Feedback",
    url: "/Feedback",
    test: "this is Feedback",
  },
  {
    id: 12,
    image:"../images/emergency.png",
    title: "Emergency",
    url: "/Emergency",
    test: "this is Emergency",
  },
  {
    id: 13,
    image:"../images/contact.png",
    title: "Expenses",
    url: "/Expenses",
    test: "this is Expenses",
  },
];
