const CardList = [
  {
    id: 1,
    title: "Goals",
    month:"12 Months",
    image: "../../images/goals.png",
    no1: "23 ",
    tagname1: "Completed ",
    no2: "35 ",
    tagname2: "Created",
  },
  {
    id: 2,
    title: "Polls",
    image: "../images/polls.png",
    no1: "12",
    tagname1: "Closed",
    no2: "35",
    tagname2: "Created",
  },
  {
    id: 3,
    title: "Events",
    image: "../images/events.png",
    no1: "07",
    tagname1: "Upcoming",
    no2: "15",
    tagname2: "Past",
  },
  {
    id: 4,
    title: "Usage",
    image: "../images/usage.png",
    no1: "44",
    tagname1: "Users",
    no2: "15",
    tagname2: "Pending",
  },
  {
    id: 5,
    title: "Profile",
    image: "../images/profile.png",
    no1: "45%",
    tagname1: "Completion Rate",
    no2: "",
    tagname2: "",
  },
  {
    id: 6,
    title: "Expenses",
    image: "../images/expenses.png",
    no1: "16",
    tagname1: "Pending",
    no2: "35",
    tagname2: "Submitted",
  },
];

export default CardList;